
import { GoogleGenAI } from "@google/genai";

const MODEL_NAME = 'gemini-2.5-flash-image';

export const generateHeadshot = async (
  base64Image: string,
  stylePrompt: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  // Clean up the base64 string to get only the data
  const imageData = base64Image.split(',')[1] || base64Image;

  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: {
      parts: [
        {
          inlineData: {
            data: imageData,
            mimeType: 'image/png',
          },
        },
        {
          text: `Transform this person into a professional headshot using this style: ${stylePrompt}. Maintain the person's facial features and identity strictly while updating their clothing and the background to match the professional style.`,
        },
      ],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error('No image was generated by the model.');
};

export const editHeadshot = async (
  currentImageBase64: string,
  editPrompt: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const imageData = currentImageBase64.split(',')[1] || currentImageBase64;

  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: {
      parts: [
        {
          inlineData: {
            data: imageData,
            mimeType: 'image/png',
          },
        },
        {
          text: `Modify this headshot based on the following request: ${editPrompt}. Ensure the professional quality and the person's likeness are preserved.`,
        },
      ],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error('No edited image was generated.');
};
